# Generated by Django 5.1.7 on 2025-04-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_collegeclass_department_subject_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_assigned',
        ),
        migrations.AddField(
            model_name='subject',
            name='class_assigned',
            field=models.ManyToManyField(related_name='subjects', to='data.collegeclass'),
        ),
    ]
