# Generated by Django 5.1.7 on 2025-04-18 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_student_department'),
        ('data', '0006_remove_subject_class_assigned_subject_class_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeclass',
            name='class_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_classes', to='accounts.teacher'),
        ),
    ]
